version: '2'
services:     
  mongo:
    image: mongo:3.4.20
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
    volumes:
      - ./_dev/mongo:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  rabbit1:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
